<?php
$this->css(array(
    $this->assetModule('css/admin.css'),
    $this->assetModule('script/system-ui.css', 'system'),
));
$this->jQuery();
$this->js($this->assetModule('script/system-msg.js', 'system'));
?>
<div class="clearfix">
    <?php if (!empty($list)) { ?>
        <h3><?php _e('List of texts'); ?></h3>
        <div id="text-list" class="clearfix media-list">

            <table id="text-list" class="table table-striped table-bordered table-condensed">
                <tr>
                    <th><?php _e('ID'); ?></th>
                    <th class="col-md-2"><?php _e('Information'); ?></th>
                    <th class="col-md-8"><?php _e('Information'); ?></th>
                    <th><?php _e('Action'); ?></th>
                </tr>
                <?php foreach ($list as $text) { ?>
                    <?php
                    if ($text['status'] == 1) {
                        $labelIdClass = 'label-success';
                    } else {
                        $labelIdClass = 'label-warning';
                    }
                    ?>
                    <tr>
                        <td>
                            <span class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($text['id']); ?></span>
                        </td>
                        <td class="text-center">
                            <div class="clearfix">
                                <?php echo $text['avatar']; ?>
                            </div>
                            <div class="clearfix">
                                <?php echo $this->escape($text['name']); ?>
                            </div>
                            <div class="clearfix">
                                <?php echo $this->escape($text['time_create_view']); ?>
                            </div>
                        </td>
                        <td>
                            <?php if (!empty($text['title'])) { ?>
                                <p><?php echo $this->escape($text['title']); ?></p>
                            <?php } ?>
                            <div class="clearfix">
                                <?php echo $text['text_description']; ?>
                            </div>
                        </td>
                        <td class="text-action text-center">
                            <a class="btn btn-primary btn-xs" title="<?php _e('Edit'); ?>"
                               href="<?php echo $this->url('', array('action' => 'update', 'id' => $text['id'])); ?>"><i
                                        class="fa fa-edit"></i> <?php _e('Edit'); ?></a>
                            <?php if ($text['status'] == 1) { ?>
                                <button id="button-<?php echo $text['id']; ?>" type="button"
                                        class="btn btn-warning btn-xs" data-toggle="button"
                                        data-link="<?php echo $this->url('', array('action' => 'accept', 'id' => $text['id'], 'status' => '2')); ?>">
                                    <i class="fa fa-trash-o"></i> <?php _e('Reject'); ?></button>
                            <?php } elseif (in_array($text['status'], array(2, 3, 4))) { ?>
                                <button id="button-<?php echo $text['id']; ?>" type="button"
                                        class="btn btn-success btn-xs" data-toggle="button"
                                        data-link="<?php echo $this->url('', array('action' => 'accept', 'id' => $text['id'], 'status' => '1')); ?>">
                                    <i class="fa fa-check"></i> <?php _e('Accept'); ?></button>
                            <?php } ?>
                        </td>
                    </tr>
                <?php } ?>
            </table>
        </div>
        <div class="paginator">
            <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator'); ?>
        </div>
    <?php } else { ?>
        <div class="alert alert-danger" role="alert">
            <?php _e('No one still send any feedback from your website, please wait from people to send feedback, or if you have feedback from other source , you can add it manually on system'); ?>
        </div>
    <?php } ?>
</div>
<script type="text/javascript">
    (function ($) {
        $("#text-list").on("click", ".text-action button", function () {
            systemMessage.wait("<?php _e('Accept text in process'); ?>");
            $.getJSON($(this).attr("data-link")).done(function (result) {
                if (result.ajaxstatus == 1) {
                    if (result.storystatus == 1) {
                        var labelClass = 'label label-success';
                        var buttonClass = 'btn btn-warning btn-xs disabled';
                        var buttonText = '<i class="fa fa-trash-o"></i> <?php _e("Reject"); ?>';
                    }
                    if (result.storystatus == 2) {
                        var labelClass = 'label label-warning';
                        var buttonClass = 'btn btn-success btn-xs disabled';
                        var buttonText = '<i class="fa fa-check"></i> <?php _e("Accept"); ?>';
                    }
                    $('#label-' + result.id).attr('class', labelClass);
                    $('#button-' + result.id).attr('class', buttonClass).html(buttonText);
                    systemMessage.succ(result.message);
                } else {
                    systemMessage.fail(result.message);
                }
            });
        });
    })(jQuery)
</script>