<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="clearfix">
    <div class="clearfix row">
        <ul class="list-inline clearfix">
            <li class="col-md-3">
                <h1><?php _e('List of texts'); ?></h1>
            </li>
            <li class="col-md-9">
                <a class="btn btn-success text-left pull-left" title="<?php _e('Submit'); ?>" href="<?php echo Pi::url($this->url('', array(
                    'controller' => 'submit',
                    'action' => 'index',
                ))); ?>"><?php _e('Submit'); ?></a>
            </li>
        </ul>
    </div>
    <div class="clearfix media-list">
        <?php foreach ($list as $text) { ?>
            <div class="media">
                <div class="media-left col-md-2 text-center">
                    <?php echo $text['avatar']; ?>
                    <p><?php echo $this->escape($text['name']); ?></p>
                </div>
                <div class="media-body">
                    <h2 class="media-heading">
                        <?php echo $this->escape($text['title']); ?>
                    </h2>
                    <?php echo $text['text_description']; ?>
                </div>
            </div>
        <?php } ?>
    </div>
    <div class="paginator">
        <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator'); ?>
    </div>
</div>